### ISSUE TITLE
Implement Checkmate and Stalemate 

### ISSUE THREAD

**Issue by SachinVarghese** [glindsell/go-alice-chess#3]
The random game play needs to display checkmate positions and stalemate positions.

**Comment by glindsell** [comment]
[This PR](https://github.com/glindsell/go-alice-chess/pull/6) appears to have fixed the problem where during random play one player would end up in check but this would not be recognised.

Random games now seem to play through until the move limit is reached, or a checkmate or stalemate occurs.
